<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZtZ14yY\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZtZ14yY/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZtZ14yY.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZtZ14yY\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerZtZ14yY\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'ZtZ14yY',
    'container.build_id' => '3fb3b1ff',
    'container.build_time' => 1563535930,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZtZ14yY');
